CREATE TABLE FUNCIONARIO(
	ID			UNIQUEIDENTIFIER	NOT NULL,
	NOME		NVARCHAR(150)		NOT NULL,
	MATRICULA	NVARCHAR(6)			NOT NULL,
	CPF			NVARCHAR(11)		NOT NULL UNIQUE,
	PRIMARY KEY(ID))
GO

-- CRIANDO UMA PROC PARA CADASTRAR UM FUNCIONARIO
CREATE PROCEDURE SP_INSERIRFUNCIONARIO
	@NOME		NVARCHAR(150),
	@MATRICULA	NVARCHAR(6),
	@CPF		NVARCHAR(11)
AS BEGIN
	BEGIN TRANSACTION --ABRINDO UMA TRANSAÇÃO
		INSERT INTO FUNCIONARIO(ID, NOME, MATRICULA, CPF)
		VALUES(NEWID(), @NOME, @MATRICULA, @CPF)
	COMMIT --FINALIZANDO E EXECUTANDO A TRANSAÇÃO
END
GO

--CRIANDO UMA PROC PARA ATUALIZAR UM FUNCIONARIO
CREATE PROCEDURE SP_ATUALIZARFUNCIONARIO
	@ID			UNIQUEIDENTIFIER,
	@NOME		NVARCHAR(150),
	@MATRICULA	NVARCHAR(6),
	@CPF		NVARCHAR(11)
AS BEGIN
	BEGIN TRANSACTION --ABRINDO UMA TRANSAÇÃO
		UPDATE FUNCIONARIO SET
			NOME = @NOME,
			MATRICULA = @MATRICULA,
			CPF = @CPF
		WHERE
			ID = @ID
	COMMIT --FINALIZANDO E EXECUTANDO A TRANSAÇÃO
END
GO

--CRIANDO UMA PROC PARA EXLUIR UM FUNCIONARIO
CREATE PROCEDURE SP_EXCLUIRFUNCIONRAIONARIO
	@ID			UNIQUEIDENTIFIER
AS BEGIN
		BEGIN TRANSACTION
		DELETE FUNCIONARIO WHERE ID = @ID
		COMMIT
END
GO